# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3dfa7f2689253f3ba1e09e93aeb5413463179472956133a2905cd47cad544b4558268b349b3879581f59b930cbc9d79649b7a19ea9d3afdbe0b31b7b08a1fc0a

test:
  secret_key_base: 9a143a50c6f243f1650271438debe2c7eed8b364d2d2f2870fdb47280c414709f9386bff60df3ec6ba4d387e35687d4f16be5a43efef4d93f2a9b17c47a05db5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
